import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Arya Kue Snack - Menu",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: '/images/logo.png',
      href: '/images/logo.png',
    },
  },
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <section className="mt-24 mb-6 mx-auto bg-gray-50">
        <div className="max-w-6xl mx-auto">
          {children}
        </div>
    </section>
  )
}