import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: "Arya's Delights - Adel",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: '/images/logo.png',
      href: '/images/logo.png',
    },
  },
};

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
