import UserTabs from "@/components/layout/UserTabs";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Arya Kue Snack - Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: '/images/logo.png',
      href: '/images/logo.png',
    },
  },
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <section className="mt-24 mb-6 mx-auto">
        <UserTabs />
        <div className="max-w-5xl mx-auto">
            {children}
        </div>
    </section>
  )
}